import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#e5e2e1",
        "on-primary-container": "#79bb87",
        "secondary-fixed-dim": "#e9c349",
        "surface": "#131313",
        "tertiary-container": "#414040",
        "surface-container": "#201f1f",
        "primary-fixed-dim": "#93d6a0",
        "surface-tint": "#93d6a0",
        "on-tertiary": "#313030",
        "primary": "#93d6a0",
        "inverse-surface": "#e5e2e1",
        "on-primary": "#003919",
        "error": "#ffb4ab",
        "on-tertiary-container": "#aeacab",
        "tertiary": "#c9c6c5",
        "on-surface": "#e5e2e1",
        "on-primary-fixed": "#00210c",
        "on-error-container": "#ffdad6",
        "secondary-container": "#af8d11",
        "primary-container": "#004b23",
        "surface-bright": "#3a3939",
        "outline": "#8a9389",
        "on-tertiary-fixed-variant": "#474646",
        "on-secondary-container": "#342800",
        "surface-container-high": "#2a2a2a",
        "on-surface-variant": "#c0c9be",
        "on-tertiary-fixed": "#1c1b1b",
        "surface-container-low": "#1c1b1b",
        "on-error": "#690005",
        "on-secondary-fixed": "#241a00",
        "error-container": "#93000a",
        "inverse-primary": "#2a6a3f",
        "tertiary-fixed-dim": "#c9c6c5",
        "on-background": "#e5e2e1",
        "primary-fixed": "#aef2bb",
        "secondary": "#e9c349",
        "on-primary-fixed-variant": "#0b5229",
        "outline-variant": "#404941",
        "background": "#131313",
        "on-secondary-fixed-variant": "#574500",
        "inverse-on-surface": "#313030",
        "surface-dim": "#131313",
        "on-secondary": "#3c2f00",
        "secondary-fixed": "#ffe088",
        "surface-variant": "#353534",
        "surface-container-highest": "#353534",
        "surface-container-lowest": "#0e0e0e",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
export default config;
